/* GET LOCATIONS SELECT LIST */
export const GET_LOCATIONS_SELECT_LIST = 'GET_LOCATIONS_SELECT_LIST';
export const GET_LOCATIONS_SELECT_LIST_SUCCESS = 'GET_LOCATIONS_SELECT_LIST_SUCCESS';
export const GET_LOCATIONS_SELECT_LIST_FAILURE = 'GET_LOCATIONS_SELECT_LIST_FAILURE';