/* ACCOUNT IMPERSONATION */
export const BACK_TO_IMPERSONATOR = 'BACK_TO_IMPERSONATOR';
export const BACK_TO_IMPERSONATOR_SUCCESS = 'BACK_TO_IMPERSONATOR_SUCCESS';
export const BACK_TO_IMPERSONATOR_FAILURE = 'BACK_TO_IMPERSONATOR_FAILURE';

export const IMPERSONATE_SIGNIN = 'IMPERSONATE_SIGNIN';
export const IMPERSONATE_SIGNIN_SUCCESS = 'IMPERSONATE_SIGNIN_SUCCESS';
export const IMPERSONATE_SIGNIN_FAILURE = 'IMPERSONATE_SIGNIN_FAILURE';

/* SWITCH TO USER ACCOUNT */
export const SWITCH_TO_USER = 'SWITCH_TO_USER';
export const SWITCH_TO_USER_SUCCESS = 'SWITCH_TO_USER_SUCCESS';
export const SWITCH_TO_USER_FAILURE = 'SWITCH_TO_USER_FAILURE';