/* NOTIFICATIONS */
export const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_FAILURE = 'GET_USER_NOTIFICATIONS_FAILURE';

/* SET ALL NOTIFICATIONS AS READ */
export const SET_ALL_NOTIFICATIONS_AS_READ = 'SET_ALL_NOTIFICATIONS_AS_READ';
export const SET_ALL_NOTIFICATIONS_AS_READ_SUCCESS = 'SET_ALL_NOTIFICATIONS_AS_READ_SUCCESS';
export const SET_ALL_NOTIFICATIONS_AS_READ_FAILURE = 'SET_ALL_NOTIFICATIONS_AS_READ_FAILURE';

/* SET NOTIFICATION AS READ */
export const SET_NOTIFICATION_AS_READ = 'SET_NOTIFICATION_AS_READ';
export const SET_NOTIFICATION_AS_READ_SUCCESS = 'SET_NOTIFICATION_AS_READ_SUCCESS';
export const SET_NOTIFICATION_AS_READ_FAILURE = 'SET_NOTIFICATION_AS_READ_FAILURE';
