/* USER PROFILE */
export const GET_USER_PROFILE_SETTINGS = 'GET_USER_PROFILE_SETTINGS';
export const GET_USER_PROFILE_SETTINGS_SUCCESS = 'GET_USER_PROFILE_SETTINGS_SUCCESS';
export const GET_USER_PROFILE_SETTINGS_FAILURE = 'GET_USER_PROFILE_SETTINGS_FAILURE';