/* USER PROFILE */
export const GET_USER_PROFILE_SETTINGS = 'GET_USER_PROFILE_SETTINGS';
export const GET_USER_PROFILE_SETTINGS_SUCCESS = 'GET_USER_PROFILE_SETTINGS_SUCCESS';
export const GET_USER_PROFILE_SETTINGS_FAILURE = 'GET_USER_PROFILE_SETTINGS_FAILURE';

/* CHANGE PASSWORD */
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const RESET_CHANGE_PASSWORD_STATE = 'RESET_CHANGE_PASSWORD_STATE';

/* UPLOAD PROFILE PICTURE FILE */
export const UPLOAD_PROFILE_PICTURE_FILE = 'UPLOAD_PROFILE_PICTURE_FILE';
export const UPLOAD_PROFILE_PICTURE_FILE_SUCCESS = 'UPLOAD_PROFILE_PICTURE_FILE_SUCCESS';
export const UPLOAD_PROFILE_PICTURE_FILE_FAILURE = 'UPLOAD_PROFILE_PICTURE_FILE_FAILURE';
export const RESET_UPLOAD_PROFILE_PICTURE_FILE_STATE = 'RESET_UPLOAD_PROFILE_PICTURE_FILE_STATE';