/* DESIGNATIONS SELECT LIST */
export const GET_DESIGNATIONS_SELECT_LIST = 'GET_DESIGNATIONS_SELECT_LIST';
export const GET_DESIGNATIONS_SELECT_LIST_SUCCESS = 'GET_DESIGNATIONS_SELECT_LIST_SUCCESS';
export const GET_DESIGNATIONS_SELECT_LIST_FAILURE = 'GET_DESIGNATIONS_SELECT_LIST_FAILURE';