/* GET UNIT OF MEASURES SELECT LIST */
export const GET_UNIT_OF_MEASURES_SELECT_LIST = 'GET_UNIT_OF_MEASURES_SELECT_LIST';
export const GET_UNIT_OF_MEASURES_SELECT_LIST_SUCCESS = 'GET_UNIT_OF_MEASURES_SELECT_LIST_SUCCESS';
export const GET_UNIT_OF_MEASURES_SELECT_LIST_FAILURE = 'GET_UNIT_OF_MEASURES_SELECT_LIST_FAILURE';