/* VEHICLE CATEGORIES */
export const GET_VEHICLE_CATEGORIES = 'GET_VEHICLE_CATEGORIES';
export const GET_VEHICLE_CATEGORIES_SUCCESS = 'GET_VEHICLE_CATEGORIES_SUCCESS';
export const GET_VEHICLE_CATEGORIES_FAILURE = 'GET_VEHICLE_CATEGORIES_FAILURE';