/* VEHICLE CATEGORIES */
export const GET_VEHICLE_CATEGORIES = 'GET_VEHICLE_CATEGORIES';
export const GET_VEHICLE_CATEGORIES_SUCCESS = 'GET_VEHICLE_CATEGORIES_SUCCESS';
export const GET_VEHICLE_CATEGORIES_FAILURE = 'GET_VEHICLE_CATEGORIES_FAILURE';

/* BED CONSTRUCTIONS */
export const GET_BED_CONSTRUCTION_SELECT_LIST = 'GET_BED_CONSTRUCTION_SELECT_LIST';
export const GET_BED_CONSTRUCTION_SELECT_LIST_SUCCESS = 'GET_BED_CONSTRUCTION_SELECT_LIST_SUCCESS';
export const GET_BED_CONSTRUCTION_SELECT_LIST_FAILURE = 'GET_BED_CONSTRUCTION_SELECT_LIST_FAILURE';

export const GET_BED_CONSTRUCTIONS = 'GET_BED_CONSTRUCTIONS';
export const GET_BED_CONSTRUCTIONS_SUCCESS = 'GET_BED_CONSTRUCTIONS_SUCCESS';
export const GET_BED_CONSTRUCTIONS_FAILURE = 'GET_BED_CONSTRUCTIONS_FAILURE';

/* FUEL TYPES */
export const GET_FUEL_TYPE_SELECT_LIST = 'GET_FUEL_TYPE_SELECT_LIST';
export const GET_FUEL_TYPE_SELECT_LIST_SUCCESS = 'GET_FUEL_TYPE_SELECT_LIST_SUCCESS';
export const GET_FUEL_TYPE_SELECT_LIST_FAILURE = 'GET_FUEL_TYPE_SELECT_LIST_FAILURE';

/* ACTIVE TRAILERS */
export const GET_ACTIVE_TRAILERS_SELECT_LIST = 'GET_ACTIVE_TRAILERS_SELECT_LIST';
export const GET_ACTIVE_TRAILERS_SELECT_LIST_SUCCESS = 'GET_ACTIVE_TRAILERS_SELECT_LIST_SUCCESS';
export const GET_ACTIVE_TRAILERS_SELECT_LIST_FAILURE = 'GET_ACTIVE_TRAILERS_SELECT_LIST_FAILURE';

/* MAKES */
export const GET_MAKES_SELECT_LIST = 'GET_MAKES_SELECT_LIST';
export const GET_MAKES_SELECT_LIST_SUCCESS = 'GET_MAKES_SELECT_LIST_SUCCESS';
export const GET_MAKES_SELECT_LIST_FAILURE = 'GET_MAKES_SELECT_LIST_FAILURE';

/* MODELS */
export const GET_MODELS_SELECT_LIST = 'GET_MODELS_SELECT_LIST';
export const GET_MODELS_SELECT_LIST_SUCCESS = 'GET_MODELS_SELECT_LIST_SUCCESS';
export const GET_MODELS_SELECT_LIST_FAILURE = 'GET_MODELS_SELECT_LIST_FAILURE';

/* EDIT TRUCK FORM */
export const GET_TRUCK_FOR_EDIT = 'GET_TRUCK_FOR_EDIT';
export const GET_TRUCK_FOR_EDIT_SUCCESS = 'GET_TRUCK_FOR_EDIT_SUCCESS';
export const GET_TRUCK_FOR_EDIT_FAILURE = 'GET_TRUCK_FOR_EDIT_FAILURE';

/* WIALON DEVICE TYPES */
export const GET_WIALON_DEVICE_TYPES_SELECT_LIST = 'GET_WIALON_DEVICE_TYPES_SELECT_LIST';
export const GET_WIALON_DEVICE_TYPES_SELECT_LIST_SUCCESS = 'GET_WIALON_DEVICE_TYPES_SELECT_LIST_SUCCESS';
export const GET_WIALON_DEVICE_TYPES_SELECT_LIST_FAILURE = 'GET_WIALON_DEVICE_TYPES_SELECT_LIST_FAILURE';

/* EDIT TRUCK */
export const EDIT_TRUCK = 'EDIT_TRUCK';
export const EDIT_TRUCK_SUCCESS = 'EDIT_TRUCK_SUCCESS';
export const EDIT_TRUCK_FAILURE = 'EDIT_TRUCK_FAILURE';
export const EDIT_TRUCK_RESET = 'EDIT_TRUCK_RESET';

/* SET TRUCK IS OUT OF SERVICE */
export const SET_TRUCK_IS_OUT_OF_SERVICE = 'SET_TRUCK_IS_OUT_OF_SERVICE';
export const SET_TRUCK_IS_OUT_OF_SERVICE_SUCCESS = 'SET_TRUCK_IS_OUT_OF_SERVICE_SUCCESS';
export const SET_TRUCK_IS_OUT_OF_SERVICE_FAILURE = 'SET_TRUCK_IS_OUT_OF_SERVICE_FAILURE';
export const SET_TRUCK_IS_OUT_OF_SERVICE_RESET = 'SET_TRUCK_IS_OUT_OF_SERVICE_RESET';