/* SET TRAILER FOR TRACTOR */
export const SET_TRAILER_FOR_TRACTOR = 'SET_TRAILER_FOR_TRACTOR';
export const SET_TRAILER_FOR_TRACTOR_SUCCESS = 'SET_TRAILER_FOR_TRACTOR_SUCCESS';
export const SET_TRAILER_FOR_TRACTOR_FAILURE = 'SET_TRAILER_FOR_TRACTOR_FAILURE';
export const SET_TRAILER_FOR_TRACTOR_RESET = 'SET_TRAILER_FOR_TRACTOR_RESET';