/* SET TRAILER FOR TRACTOR */
export const SET_TRAILER_FOR_TRACTOR = 'SET_TRAILER_FOR_TRACTOR';
export const SET_TRAILER_FOR_TRACTOR_SUCCESS = 'SET_TRAILER_FOR_TRACTOR_SUCCESS';
export const SET_TRAILER_FOR_TRACTOR_FAILURE = 'SET_TRAILER_FOR_TRACTOR_FAILURE';
export const SET_TRAILER_FOR_TRACTOR_RESET = 'SET_TRAILER_FOR_TRACTOR_RESET';

/* SET TRACTOR FOR TRAILER */
export const SET_TRACTOR_FOR_TRAILER = 'SET_TRACTOR_FOR_TRAILER';
export const SET_TRACTOR_FOR_TRAILER_SUCCESS = 'SET_TRACTOR_FOR_TRAILER_SUCCESS';
export const SET_TRACTOR_FOR_TRAILER_FAILURE = 'SET_TRACTOR_FOR_TRAILER_FAILURE';
export const SET_TRACTOR_FOR_TRAILER_RESET = 'SET_TRACTOR_FOR_TRAILER_RESET';