// sidebar
export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';
export const GET_MENU_ITEMS_SUCCESS = 'GET_MENU_ITEMS_SUCCESS';
export const GET_MENU_ITEMS_FAILURE = 'GET_MENU_ITEMS_FAILURE';

// support link
export const GET_SUPPORT_LINK_ADDRESS = 'GET_SUPPORT_LINK_ADDRESS';
export const GET_SUPPORT_LINK_ADDRESS_SUCCESS = 'GET_SUPPORT_LINK_ADDRESS_SUCCESS';
export const GET_SUPPORT_LINK_ADDRESS_FAILURE = 'GET_SUPPORT_LINK_ADDRESS_FAILURE';