/* PAGE CONFIG */
export const GET_PAGE_CONFIG = 'GET_PAGE_CONFIG';
export const GET_PAGE_CONFIG_SUCCESS = 'GET_PAGE_CONFIG_SUCCESS';
export const GET_PAGE_CONFIG_FAILURE = 'GET_PAGE_CONFIG_FAILURE';

/* SCHEDULE TRUCKS */
export const GET_SCHEDULE_TRUCKS = 'GET_SCHEDULE_TRUCKS';
export const GET_SCHEDULE_TRUCKS_SUCCESS = 'GET_SCHEDULE_TRUCKS_SUCCESS';
export const GET_SCHEDULE_TRUCKS_FAILURE = 'GET_SCHEDULE_TRUCKS_FAILURE';
export const GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST = 'GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST';
export const GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_SUCCESS = 'GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_SUCCESS';
export const GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_FAILURE = 'GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_FAILURE';
export const GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_RESET = 'GET_SCHEDULE_TRUCK_BY_SYNC_REQUEST_RESET';

/* REMOVE TRUCK FROM SCHEDULE */
export const REMOVE_TRUCK_FROM_SCHEDULE = 'REMOVE_TRUCK_FROM_SCHEDULE';

/* SCHEDULE ORDERS */
export const GET_SCHEDULE_ORDERS = 'GET_SCHEDULE_ORDERS';
export const GET_SCHEDULE_ORDERS_SUCCESS = 'GET_SCHEDULE_ORDERS_SUCCESS';
export const GET_SCHEDULE_ORDERS_FAILURE = 'GET_SCHEDULE_ORDERS_FAILURE';