/* SCHEDULE TRUCKS */
export const GET_SCHEDULE_TRUCKS = 'GET_SCHEDULE_TRUCKS';
export const GET_SCHEDULE_TRUCKS_SUCCESS = 'GET_SCHEDULE_TRUCKS_SUCCESS';
export const GET_SCHEDULE_TRUCKS_FAILURE = 'GET_SCHEDULE_TRUCKS_FAILURE';

/* SCHEDULE ORDERS */
export const GET_SCHEDULE_ORDERS = 'GET_SCHEDULE_ORDERS';
export const GET_SCHEDULE_ORDERS_SUCCESS = 'GET_SCHEDULE_ORDERS_SUCCESS';
export const GET_SCHEDULE_ORDERS_FAILURE = 'GET_SCHEDULE_ORDERS_FAILURE';