/* EDIT DRIVER FORM */
export const GET_DRIVER_FOR_EDIT = 'GET_DRIVER_FOR_EDIT';
export const GET_DRIVER_FOR_EDIT_SUCCESS = 'GET_DRIVER_FOR_EDIT_SUCCESS';
export const GET_DRIVER_FOR_EDIT_FAILURE = 'GET_DRIVER_FOR_EDIT_FAILURE';

/* GET DRIVERS SELECT LIST */
export const GET_DRIVERS_SELECT_LIST = 'GET_DRIVERS_SELECT_LIST';
export const GET_DRIVERS_SELECT_LIST_SUCCESS = 'GET_DRIVERS_SELECT_LIST_SUCCESS';
export const GET_DRIVERS_SELECT_LIST_FAILURE = 'GET_DRIVERS_SELECT_LIST_FAILURE';

/* EDIT DRIVER */
export const EDIT_DRIVER = 'EDIT_DRIVER';
export const EDIT_DRIVER_SUCCESS = 'EDIT_DRIVER_SUCCESS';
export const EDIT_DRIVER_FAILURE = 'EDIT_DRIVER_FAILURE';