/* DRIVERS */
export const GET_DRIVERS_SELECT_LIST = 'GET_DRIVERS_SELECT_LIST';
export const GET_DRIVERS_SELECT_LIST_SUCCESS = 'GET_DRIVERS_SELECT_LIST_SUCCESS';
export const GET_DRIVERS_SELECT_LIST_FAILURE = 'GET_DRIVERS_SELECT_LIST_FAILURE';