/* TENANT SETTINGS */
export const GET_TENANT_SETTINGS = 'GET_TENANT_SETTINGS';
export const GET_TENANT_SETTINGS_SUCCESS = 'GET_TENANT_SETTINGS_SUCCESS';
export const GET_TENANT_SETTINGS_FAILURE = 'GET_TENANT_SETTINGS_FAILURE';