/* FEATURES */
export const CHECK_IF_ENABLED = 'CHECK_IF_ENABLED';
export const CHECK_IF_ENABLED_SUCCESS = 'CHECK_IF_ENABLED_SUCCESS';
export const CHECK_IF_ENABLED_FAILURE = 'CHECK_IF_ENABLED_FAILURE';