/* LINKED USERS */
export const GET_LINKED_USERS = 'GET_LINKED_USERS';
export const GET_LINKED_USERS_SUCCESS = 'GET_LINKED_USERS_SUCCESS';
export const GET_LINKED_USERS_FAILURE = 'GET_LINKED_USERS_FAILURE';

/* LINK TO USER */
export const LINK_TO_USER = 'LINK_TO_USER';
export const LINK_TO_USER_SUCCESS = 'LINK_TO_USER_SUCCESS';
export const LINK_TO_USER_FAILURE = 'LINK_TO_USER_FAILURE';
export const LINK_TO_USER_RESET = 'LINK_TO_USER_RESET';

/* UNLINK USER */
export const UNLINK_USER = 'UNLINK_USER';
export const UNLINK_USER_SUCCESS = 'UNLINK_USER_SUCCESS';
export const UNLINK_USER_FAILURE = 'UNLINK_USER_FAILURE';
export const UNLINK_USER_RESET = 'UNLINK_USER_RESET';