/* LINKED USERS */
export const GET_LINKED_USERS = 'GET_LINKED_USERS';
export const GET_LINKED_USERS_SUCCESS = 'GET_LINKED_USERS_SUCCESS';
export const GET_LINKED_USERS_FAILURE = 'GET_LINKED_USERS_FAILURE';