/* GET UNITS OF MEASURE SELECT LIST */
export const GET_UNITS_OF_MEASURE_SELECT_LIST = 'GET_UNITS_OF_MEASURE_SELECT_LIST';
export const GET_UNITS_OF_MEASURE_SELECT_LIST_SUCCESS = 'GET_UNITS_OF_MEASURE_SELECT_LIST_SUCCESS';
export const GET_UNITS_OF_MEASURE_SELECT_LIST_FAILURE = 'GET_UNITS_OF_MEASURE_SELECT_LIST_FAILURE';