/* LEASE HAULER DRIVERS SELECT LIST */
export const GET_LEASE_HAULER_DRIVERS_SELECT_LIST = 'GET_LEASE_HAULER_DRIVERS_SELECT_LIST';
export const GET_LEASE_HAULER_DRIVERS_SELECT_LIST_SUCCESS = 'GET_LEASE_HAULER_DRIVERS_SELECT_LIST_SUCCESS';
export const GET_LEASE_HAULER_DRIVERS_SELECT_LIST_FAILURE = 'GET_LEASE_HAULER_DRIVERS_SELECT_LIST_FAILURE';