/* GET SERVICES WITH TAX INFO SELECT LIST */
export const GET_SERVICES_WITH_TAX_INFO_SELECT_LIST = 'GET_SERVICES_WITH_TAX_INFO_SELECT_LIST';
export const GET_SERVICES_WITH_TAX_INFO_SELECT_LIST_SUCCESS = 'GET_SERVICES_WITH_TAX_INFO_SELECT_LIST_SUCCESS';
export const GET_SERVICES_WITH_TAX_INFO_SELECT_LIST_FAILURE = 'GET_SERVICES_WITH_TAX_INFO_SELECT_LIST_FAILURE';