/* SET DRIVER FOR TRUCK */
export const SET_DRIVER_FOR_TRUCK = 'SET_DRIVER_FOR_TRUCK';
export const SET_DRIVER_FOR_TRUCK_SUCCESS = 'SET_DRIVER_FOR_TRUCK_SUCCESS';
export const SET_DRIVER_FOR_TRUCK_FAILURE = 'SET_DRIVER_FOR_TRUCK_FAILURE';
export const SET_DRIVER_FOR_TRUCK_RESET = 'SET_DRIVER_FOR_TRUCK_RESET';

/* HAS ORDER LINE TRUCKS */
export const HAS_ORDER_LINE_TRUCKS = 'HAS_ORDER_LINE_TRUCKS';
export const HAS_ORDER_LINE_TRUCKS_SUCCESS = 'HAS_ORDER_LINE_TRUCKS_SUCCESS';
export const HAS_ORDER_LINE_TRUCKS_FAILURE = 'HAS_ORDER_LINE_TRUCKS_FAILURE';
export const HAS_ORDER_LINE_TRUCKS_RESET = 'HAS_ORDER_LINE_TRUCKS_RESET';