/* SET DRIVER FOR TRUCK */
export const SET_DRIVER_FOR_TRUCK = 'SET_DRIVER_FOR_TRUCK';
export const SET_DRIVER_FOR_TRUCK_SUCCESS = 'SET_DRIVER_FOR_TRUCK_SUCCESS';
export const SET_DRIVER_FOR_TRUCK_FAILURE = 'SET_DRIVER_FOR_TRUCK_FAILURE';
export const SET_DRIVER_FOR_TRUCK_RESET = 'SET_DRIVER_FOR_TRUCK_RESET';