/* ACTIVE CUSTOMERS SELECT LIST */
export const GET_ACTIVE_CUSTOMERS_SELECT_LIST = 'GET_ACTIVE_CUSTOMERS_SELECT_LIST';
export const GET_ACTIVE_CUSTOMERS_SELECT_LIST_SUCCESS = 'GET_ACTIVE_CUSTOMERS_SELECT_LIST_SUCCESS';
export const GET_ACTIVE_CUSTOMERS_SELECT_LIST_FAILURE = 'GET_ACTIVE_CUSTOMERS_SELECT_LIST_FAILURE';