/* GET ORDER PRIORITY SELECT LIST */
export const GET_ORDER_PRIORITY_SELECT_LIST = 'GET_ORDER_PRIORITY_SELECT_LIST';
export const GET_ORDER_PRIORITY_SELECT_LIST_SUCCESS = 'GET_ORDER_PRIORITY_SELECT_LIST_SUCCESS';
export const GET_ORDER_PRIORITY_SELECT_LIST_FAILURE = 'GET_ORDER_PRIORITY_SELECT_LIST_FAILURE';

/* EDIT JOB FORM */
export const GET_JOB_FOR_EDIT = 'GET_JOB_FOR_EDIT';
export const GET_JOB_FOR_EDIT_SUCCESS = 'GET_JOB_FOR_EDIT_SUCCESS';
export const GET_JOB_FOR_EDIT_FAILURE = 'GET_JOB_FOR_EDIT_FAILURE';

/* EDIT ORDER FORM */
export const GET_ORDER_FOR_EDIT = 'GET_ORDER_FOR_EDIT';
export const GET_ORDER_FOR_EDIT_SUCCESS = 'GET_ORDER_FOR_EDIT_SUCCESS';
export const GET_ORDER_FOR_EDIT_FAILURE = 'GET_ORDER_FOR_EDIT_FAILURE';