/* EDIT ORDER FORM */
export const GET_ORDER_FOR_EDIT = 'GET_ORDER_FOR_EDIT';
export const GET_ORDER_FOR_EDIT_SUCCESS = 'GET_ORDER_FOR_EDIT_SUCCESS';
export const GET_ORDER_FOR_EDIT_FAILURE = 'GET_ORDER_FOR_EDIT_FAILURE';