/* USER INFO */
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

/* USER PROFILE MENU */
export const GET_USER_PROFILE_MENU = 'GET_USER_PROFILE_MENU';
export const GET_USER_PROFILE_MENU_SUCCESS = 'GET_USER_PROFILE_MENU_SUCCESS';
export const GET_USER_PROFILE_MENU_FAILURE = 'GET_USER_PROFILE_MENU_FAILURE';

/* USER SETTING */
export const GET_USER_SETTING = 'GET_USER_SETTING';
export const GET_USER_SETTING_SUCCESS = 'GET_USER_SETTING_SUCCESS';
export const GET_USER_SETTING_FAILURE = 'GET_USER_SETTING_FAILURE';