/* USER INFO */
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

/* USER APP SETTINGS */
export const GET_USER_APP_CONFIG = 'GET_USER_APP_CONFIG';
export const GET_USER_APP_CONFIG_SUCCESS = 'GET_USER_APP_CONFIG_SUCCESS';
export const GET_USER_APP_CONFIG_FAILURE = 'GET_USER_APP_CONFIG_FAILURE';

/* USER GENERAL SETTINGS */
export const GET_USER_GENERAL_SETTINGS = 'GET_USER_GENERAL_SETTINGS';
export const GET_USER_GENERAL_SETTINGS_SUCCESS = 'GET_USER_GENERAL_SETTINGS_SUCCESS';
export const GET_USER_GENERAL_SETTINGS_FAILURE = 'GET_USER_GENERAL_SETTINGS_FAILURE';

/* USER SETTING */
export const GET_USER_SETTING = 'GET_USER_SETTING';
export const GET_USER_SETTING_SUCCESS = 'GET_USER_SETTING_SUCCESS';
export const GET_USER_SETTING_FAILURE = 'GET_USER_SETTING_FAILURE';

/* USER PROFILE MENU */
export const GET_USER_PROFILE_MENU = 'GET_USER_PROFILE_MENU';
export const GET_USER_PROFILE_MENU_SUCCESS = 'GET_USER_PROFILE_MENU_SUCCESS';
export const GET_USER_PROFILE_MENU_FAILURE = 'GET_USER_PROFILE_MENU_FAILURE';